### ISSUE TITLE
Conflict between AllowedPattern and ConstraintDescription

### ISSUE THREAD

**Issue by DanBloy** [aws-quickstart/connect-integration-spicecsm#5]
The below CFT code conflicts between AllowedPattern (Doens't allow '/') and ConstraintDescription (Requests '/')

Parameters:
  SpiceCSMSubdomain:
    AllowedPattern: **^[a-z]+$**
    ConstraintDescription: SpiceCSM subdomain can include numbers, lowercase letters,
      uppercase letters. **It must start with a slash (/).**
    Default: yourcompany
    Description: The subdomain of your SpiceCSM instance
    Type: String

**Comment by santiagocardenas** [comment]
Thanks for the feedback @DanBloy . Seems like we forgot to update the ConstraintDescription.

@jayyeras please take a look.
